spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.235.135.26:3306/user_center
    username: liang
    password: 325176
  # session失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0

